sonar.projectKey=janrothen_btc-ticker
sonar.organization=janrothen

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=src/btcticker/lib/**
